name: React project Artifact

on:
  push:
    branches:
      - main
    paths:
      - "react-appl/**"  

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
    run:
      working-directory: react-appl
    steps:  
      - name: Create file
        run : echo "Hello from GitHub Actions" > output.txt 
     
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Node Js
        uses: actions/setup-node@v6

      - name: Install Dependencies
        run: npm run build

      - name: Upload an Artifact
        run: actions/upload-artifact@v4
        with: 
           name: react-build
           path: react-appl/dist




